### PR TITLE
Venly pr 1

### PR DESCRIPTION
**Pull request by abdullahvenly**
First PR which includes:

- Intro Page

- Wallet API Guide

### CODE REVIEW

**Comment by Dilrong** [comment]
`ERROR 2024/06/03 13:09:34 Image image.png is missing and not external for page develop/develop/venly-tools/wallet-api.md` 
I got a build error, can you check it out?

**Comment by abdullahvenly** [comment]
@Dilrong I've updated the image and now the build succeeded.

**Review by junhee0 — APPROVED** [review]

**Comment by abdullahvenly** [comment]
Hi, @Dilrong @junhee0, all checks have passed for this PR. Can you kindly merge it?

If it is missing something please let me know, thanks.

**Comment by Dilrong** [comment]
I'm a contributor, not a maintainer. Thank you!

**Pull request closed without merging**
