### PR TITLE
fix: gas-price policy

### PR DESCRIPTION
**Pull request by nowooj**

### CODE REVIEW

**Comment by psy2848048** [comment]
https://github.com/xpladev/docs/blob/main/content/en/develop/develop/core-modules/auth.md

As `min_gas_price` is parametrized, does the arg `--minimum-gas-prices=850000000000axpla` work?

**Comment by psy2848048** [comment]
https://github.com/xpladev/docs/blob/fix/gas-price-policy/content/en/develop/develop/core-modules/evm.md

Typo list

- 68th line
  - highter -> higher
  - execption -> exception

- 70th: discareded -> discarded
- 94th: overides -> overrides
- 101th: implementatiom -> implementation
- 364th: formated -> formatted
- 441st: sucessfully -> successfully
- 486th: MsgEthreumTx -> MsgEthereumTx
- 596th: negaitve -> negative
- 598th: negaitve -> negative

**Comment by psy2848048** [comment]
https://github.com/xpladev/docs/blob/fix/gas-price-policy/content/en/full-node/full-node/manage-a-validator/overview.md

Seems to need changing into feemarket parametrized gas price (11th line)
9th line: Top 130 validators -> set by governance

**Comment by psy2848048** [comment]
https://github.com/xpladev/docs/blob/fix/gas-price-policy/content/en/full-node/full-node/run-a-full-node/configure-general-settings.md

Please check the section related with 38th line

**Comment by psy2848048** [comment]
https://github.com/xpladev/docs/blob/fix/gas-price-policy/content/en/learn/learn/about-xpla-chain.md

90th: Please check line about gas price
53th: nit; Please consider to update the new status (Bonded - active / inactive)

https://github.com/xpladev/docs/blob/fix/gas-price-policy/content/en/learn/learn/glossary.md

Please check line 67th

-- End of the review --

**Review by psy2848048 — APPROVED** [review]

**Review by yoosah — APPROVED** [review]
lgtm

**Pull request merged**
